# -*- coding: utf-8 -*-
"""planner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xNZj-ItYI_8uknmD7JalHHnRNSWcjFJD
"""

import streamlit as st
import os
from dotenv import load_dotenv
from openai import OpenAI
from fpdf import FPDF

load_dotenv()
if os.getenv("GROQ_KEY"):
    api_key = os.getenv("GROQ_KEY")
else:
  api_key = st.secrets["GROQ_KEY"]

client = OpenAI(
    api_key=api_key,
    base_url="https://api.groq.com/openai/v1"
)

model_name = "llama-3.3-70b-versatile"

#PDF for fitness plan and shoping list--
def create_pdf(plan_text, shopping_list):
    pdf = FPDF()
    pdf.add_page()
    main_font = "Times"
    pdf.set_font(main_font, size=12)

    pdf.set_font(main_font, style="B", size=18)
    pdf.cell(200, 10, txt="My Fitness Plan", ln=True, align='C')
    pdf.ln(10)

    pdf.set_font(main_font, size=12)
    plan = plan_text.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 10, txt= plan)
    pdf.ln(10)

    pdf.set_font(main_font, style="B", size=16)
    pdf.cell(200, 10, txt="My Shopping List", ln=True, align='L')

    pdf.set_font(main_font, size=12)
    clean_list = shopping_list.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 10, txt= clean_list)

    return pdf.output(dest='S').encode('latin-1')

# Streamlit--
st.set_page_config(page_title="Fitness Planner", layout="centered")
st.title("Workout & Diet Planner")
st.markdown("Personalized plans + Grocery Lists")

with st.sidebar:
    st.header("Set Your Profile")
    age = st.number_input("Age", min_value=15, max_value=60, value=18)
    gender = st.selectbox("Gender", ["Male", "Female", "other"])
    weight = st.number_input("Weight (kg)", min_value=30.0, value=50.0)
    height = st.number_input("Height (cm)", min_value=100.0, value=150.0)

    st.divider()

    goal = st.selectbox("Fitness Goal", ["Weight Loss", "Muscle Gain", "Maintain body", "General Health"])

    target_text = ""

    if goal == "Weight Loss":
        weekly_loss = st.number_input("Target Loss per Week (kg)", min_value=0.1, max_value=1.5, value=0.5, step=0.1)
        target = f"Goal is to LOSE {weekly_loss}kg per week."
        st.caption("Recommended: 0.5kg - 1.0kg/week.")

    elif goal == "Muscle Gain":
        weekly_gain = st.number_input("Target Gain per Week (kg)", min_value=0.1, max_value=1.0, value=0.25, step=0.1)
        target = f"Goal is to GAIN {weekly_gain}kg of muscle per week."
        st.caption("Recommended: 0.25kg - 0.5kg/week .")

    else:
        target = "Goal is Maintain body/General Health."

    diet_pref = st.text_input("Cultural/Dietary Habits", placeholder="e.g., Vegan, Indian, italian")
    budget = st.selectbox("Daily Food Budget",["Low", "Moderate", "High"])
    currency = st.selectbox("Preferred Currency", ["USD ($)", "INR (₹)", "EUR (€)"])

if 'fitness_plan' not in st.session_state:
    st.session_state.fitness_plan = None
if 'shopping_list' not in st.session_state:
    st.session_state.shopping_list = None


if st.button("Generate My Plan & Grocery List"):
    with st.spinner("Creating Your Plan"):

        system_prompt = f"""
        You are a Fitness & Nutrition Coach for students.
        User: {age}y/o {gender}, {weight}kg, {height}cm.
        Primary Goal: {goal}.
        Specific Target: {target}
        Diet: {diet_pref}. Budget: {budget}. Currency: {currency}.

        Provide the response in two clear parts:

        PART 1: THE PLAN
        - Calculate daily calorie maintenance vs. target calories based on the {target_text}.
        - A weekly workout schedule (dorm-friendly/low equipment).
        - A simple meal plan (breakfast, lunch, dinner, snack).

        PART 2: GROCERY LIST & BUDGET
        - A consolidated shopping list for the week based on the meal plan.
        - Categorize items (Proteins, Carbs, Veggies).
        - Provide an ESTIMATED total weekly cost in {currency}.
        - Keep it affordable (student budget).

        Formatting:
        - Do NOT use markdown bolding (**) heavily.
        - Clearly separate Part 1 and Part 2.
        """

        try:
            response = client.chat.completions.create(
                model=model_name,
                messages=[
                    {"role": "system", "content": "You are a helpful fitness assistant."},
                    {"role": "user", "content": system_prompt}
                ],
                temperature=0.7
            )

            full_response = response.choices[0].message.content

            if "PART 2" in full_response:
                parts = full_response.split("PART 2")
                st.session_state.fitness_plan = parts[0].replace("PART 1", "").strip()
                st.session_state.shopping_list = parts[1].replace(":", "").strip()
            else:
                st.session_state.fitness_plan = full_response
                st.session_state.shopping_list = "Could not separate list. See main plan."

        except Exception as e:
            st.error(f"Error: {e}")

if st.session_state.fitness_plan:

    tab1, tab2 = st.tabs(["📅 Workout & Diet Plan", "🛒 Grocery List & Budget"])

    with tab1:
        st.subheader("Your Weekly Routine")
        st.markdown(st.session_state.fitness_plan)

    with tab2:
        st.subheader("Weekly Shopping List")
        st.info(f"Estimated for budget level: {budget}")
        st.markdown(st.session_state.shopping_list)

    st.markdown("---")

    combined_text = st.session_state.fitness_plan + "\n\n" + st.session_state.shopping_list
    pdf_bytes = create_pdf(st.session_state.fitness_plan, st.session_state.shopping_list)

    st.download_button(
        label="Download Your Plan (PDF)",
        data=pdf_bytes,
        file_name="fitness plan and grocerie list.pdf",
        mime="application/pdf")

    st.divider()
    st.subheader("💬 Ask Your Doubts")
    st.caption("Need to change the meal? Don't know an exercise? Ask here!")

    if "chat_history" not in st.session_state:
        st.session_state.chat_history = []

    for message in st.session_state.chat_history:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    if user_question := st.chat_input("Ex: I don't eat oat meal, what can I swap for breakfast?"):

        st.session_state.chat_history.append({"role": "user", "content": user_question})
        with st.chat_message("user"):
            st.markdown(user_question)

        with st.chat_message("assistant"):
            with st.spinner("Thinking..."):

                context_prompt = f"""
                You are a fitness coach. The user has a plan generated with these details:
                {st.session_state.fitness_plan}

                The user asks: "{user_question}"

                Answer briefly and helpfully based on their plan.
                """

                response = client.chat.completions.create(
                    model=model_name,
                    messages=[
                        {"role": "system", "content": "You are a helpful fitness assistant."},
                        {"role": "user", "content": context_prompt}
                    ]
                )

                answer = response.choices[0].message.content
                st.markdown(answer)
                st.session_state.chat_history.append({"role": "assistant", "content": answer})